### ISSUE TITLE
Ruff coverage tracker

### ISSUE THREAD

**Issue by OMEGARAZER** [Serene-Arc/bulk-downloader-for-reddit#793]
## Description

Coverage tracker for [ruff](https://github.com/charliermarsh/ruff) [checks](https://beta.ruff.rs/docs/)
ruff support in #806  

## Checks

* [x] [Pyflakes (F)](https://beta.ruff.rs/docs/rules/#pyflakes-f)
* [x] [pycodestyle (E)](https://beta.ruff.rs/docs/rules/#error-e)
* [x] [pycodestyle (W)](https://beta.ruff.rs/docs/rules/#warning-w)
* [ ] [mccabe (C90)](https://beta.ruff.rs/docs/rules/#mccabe-c90)
* [x] [isort (I)](https://beta.ruff.rs/docs/rules/#isort-i)
* [x] [pep8-naming (N)](https://beta.ruff.rs/docs/rules/#pep8-naming-n)
* [ ] [pydocstyle (D)](https://beta.ruff.rs/docs/rules/#pydocstyle-d)
* [x] [pyupgrade (UP)](https://beta.ruff.rs/docs/rules/#pyupgrade-up)
* [x] [flake8-2020 (YTT)](https://beta.ruff.rs/docs/rules/#flake8-2020-ytt)
* [x] [flake8-annotations (ANN)](https://beta.ruff.rs/docs/rules/#flake8-annotations-ann)
* [x] [flake8-bandit (S)](https://beta.ruff.rs/docs/rules/#flake8-bandit-s)
* [x] [flake8-blind-except (BLE)](https://beta.ruff.rs/docs/rules/#flake8-blind-except-ble)
* [ ] [flake8-boolean-trap (FBT)](https://beta.ruff.rs/docs/rules/#flake8-boolean-trap-fbt)
* [x] [flake8-bugbear (B)](https://beta.ruff.rs/docs/rules/#flake8-bugbear-b)
* [ ] [flake8-builtins (A)](https://beta.ruff.rs/docs/rules/#flake8-builtins-a)
* [ ] [flake8-commas (COM)](https://beta.ruff.rs/docs/rules/#flake8-commas-com)
* [ ] [flake8-comprehensions (C4)](https://beta.ruff.rs/docs/rules/#flake8-comprehensions-c4)
* [ ] [flake8-datetimez (DTZ)](https://beta.ruff.rs/docs/rules/#flake8-datetimez-dtz)
* [ ] [flake8-debugger (T10)](https://beta.ruff.rs/docs/rules/#flake8-debugger-t10)
~~[flake8-django (DJ)](https://beta.ruff.rs/docs/rules/#flake8-django-dj)~~
* [ ] [flake8-errmsg (EM)](https://beta.ruff.rs/docs/rules/#flake8-errmsg-em)
* [ ] [flake8-executable (EXE)](https://beta.ruff.rs/docs/rules/#flake8-executable-exe)
* [x] [flake8-implicit-str-concat (ISC)](https://beta.ruff.rs/docs/rules/#flake8-implicit-str-concat-isc)
* [x] [flake8-import-conventions (ICN)](https://beta.ruff.rs/docs/rules/#flake8-import-conventions-icn)
* [ ] [flake8-logging-format (G)](https://beta.ruff.rs/docs/rules/#flake8-logging-format-g)
* [x] [flake8-no-pep420 (INP)](https://beta.ruff.rs/docs/rules/#flake8-no-pep420-inp)
* [ ] [flake8-pie (PIE)](https://beta.ruff.rs/docs/rules/#flake8-pie-pie)
* [ ] [flake8-print (T20)](https://beta.ruff.rs/docs/rules/#flake8-print-t20)
* [ ] [flake8-pyi (PYI)](https://beta.ruff.rs/docs/rules/#flake8-pyi-pyi)
* [x] [flake8-pytest-style (PT)](https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt)
* [x] [flake8-quotes (Q)](https://beta.ruff.rs/docs/rules/#flake8-quotes-q)
* [ ] [flake8-raise (RSE)](https://beta.ruff.rs/docs/rules/#flake8-raise-rse)
* [ ] [flake8-return (RET)](https://beta.ruff.rs/docs/rules/#flake8-return-ret)
* [ ] [flake8-self (SLF)](https://beta.ruff.rs/docs/rules/#flake8-self-slf)
* [ ] [flake8-simplify (SIM)](https://beta.ruff.rs/docs/rules/#flake8-simplify-sim)
* [x] [flake8-tidy-imports (TID)](https://beta.ruff.rs/docs/rules/#flake8-tidy-imports-tid)
* [ ] [flake8-type-checking (TCH)](https://beta.ruff.rs/docs/rules/#flake8-type-checking-tch)
* [ ] [flake8-unused-arguments (ARG)](https://beta.ruff.rs/docs/rules/#flake8-unused-arguments-arg)
* [x] [flake8-use-pathlib (PTH)](https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth)
* [x] [eradicate (ERA)](https://beta.ruff.rs/docs/rules/#eradicate-era)
~~[pandas-vet (PD)](https://beta.ruff.rs/docs/rules/#pandas-vet-pd)~~
* [ ] [pygrep-hooks (PGH)](https://beta.ruff.rs/docs/rules/#pygrep-hooks-pgh)
* [ ] [Pylint Convention (PLC)](https://beta.ruff.rs/docs/rules/#convention-plc)
* [ ] [Pylint Error (PLE)](https://beta.ruff.rs/docs/rules/#error-ple)
* [ ] [Pylint Refactor (PLR)](https://beta.ruff.rs/docs/rules/#refactor-plr)
* [ ] [Pylint Warning (PLW)](https://beta.ruff.rs/docs/rules/#warning-plw)
* [ ] [tryceratops (TRY)](https://beta.ruff.rs/docs/rules/#tryceratops-try)
~~[NumPy-specific rules (NPY)](https://beta.ruff.rs/docs/rules/#numpy-specific-rules-npy)~~
* [x] [Ruff-specific rules (RUF)](https://beta.ruff.rs/docs/rules/#ruff-specific-rules-ruf)

## Some info on checks I've looked into so far that aren't complete
I crossed off some checks that are library-specific
Mccabe C90 is unlikely to be hit without some severe refactoring
Docstyle is missing quite a lot if it's going to be considered

Open to suggestions on checks to prioritize or ignore.

**Comment by Serene-Arc** [comment]
I'm concerned that we're adding a lot of different linters and checkers that don't really add much to the project. How is this one different to the other PRs that you've opened and why is it needed?

**Comment by OMEGARAZER** [comment]
> I'm concerned that we're adding a lot of different linters and checkers that don't really add much to the project.

They generally add improved code quality and error checking to the project, is that not the point of linting in the first place?

> How is this one different to the other PRs that you've opened and why is it needed?

It's not *needed*. Just like using Flake8 isn't *needed*. As I said though it's for improved code quality, same as when I suggested Refurb (I assume that's what you mean by other PRs).

> prioritize or ignore

So I take it then you're wanting to ignore everything except E9, F63, F7, F82 and I then.

**Comment by Serene-Arc** [comment]
I'm not against linters, I'm just concerned about adding a bunch of different linters that each add some overhead. Is there a fairly comprehensive linter that we can add to pre-commit, tox, etc? If we have a linter, it should be applied going forwards as well.

**Comment by OMEGARAZER** [comment]
To quote directly from the [ruff readme](https://github.com/charliermarsh/ruff/blob/main/README.md)
>Ruff aims to be orders of magnitude faster than alternative tools while integrating more functionality behind a single, common interface.
>
>Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing tens or hundreds of times faster than any individual tool.

It's one linter that implements the majority of checks from each of those separate tools/linters but is faster with all of them than the base flake8 is on its own.

**Comment by Serene-Arc** [comment]
Sorry it's taken me so long to get back to this. The semester has been brutal. Are we planning to replace flake8 with this linter or run them in tandem?

EDIT: nevermind, just read the PR and we are.
